Document: bbbdownload
Title: Debian bbbdownload Manual
Author: <insert document author here>
Abstract: This manual describes what bbbdownload is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bbbdownload/bbbdownload.sgml.gz

Format: postscript
Files: /usr/share/doc/bbbdownload/bbbdownload.ps.gz

Format: text
Files: /usr/share/doc/bbbdownload/bbbdownload.text.gz

Format: HTML
Index: /usr/share/doc/bbbdownload/html/index.html
Files: /usr/share/doc/bbbdownload/html/*.html
